# Generated by Django 4.2.5 on 2023-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_alert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetoken',
            name='access_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
